### ISSUE TITLE
Fails for simple quieries containing `__typename` 

### ISSUE THREAD

**Issue by Saicheg** [Hongbo-Miao/traefik-plugin-disable-graphql-introspection#2]
Hey @Hongbo-Miao!

Really good job on traefik plugin for GraphQL. Really appreciate it.

Playing around your plugin i realized that condition for introspection might not be perfect, since it only checks if request body has either `__type` or `__schema`.

However part of GraphQL specification is that every object can be queried for `__typename`, which can be used by clients for various reasons:

https://www.apollographql.com/docs/apollo-server/schema/schema/#the-__typename-field

This way if you simply query something like:

```
users {
  id
  __typename
}
```

It will fail with `GraphQL introspection is not allowed` if thought it is not introspection.

@Hongbo-Miao what is the best idea to fix that and how i can help you with that?

**Comment by hongbo-miao** [comment]
Hi @Saicheg One way in my mind is changing exiting "contains" to "equal to".
Feel free to contribute in any way making sense to you! 
I have given you the repo access! 😃

**Comment by Saicheg** [comment]
@Hongbo-Miao ok, i will take a look tomorrow and maybe add some tests for different cases
